### ISSUE TITLE
IndexOutOfBoundsException with N document add

### ISSUE THREAD

**Issue by stevebuik** [flaptor/indextank-java#10]
I cannot reproduce this problem in a test case yet but it is reliably reproducing in our production code. We have worked around it by reducing the number of adds but there is a bug somewhere in that addDocuments method.

Let me know if I can provide more info...

java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
    at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:579)
    at java.util.ArrayList.add(ArrayList.java:393)
    at com.flaptor.indextank.apiclient.IndexTankClient$Index.addDocuments(IndexTankClient.java:674)
    at com.pbw.cc.business.search.indextank.IndexTankV1ServiceAgentV1Impl.addDocuments(IndexTankV1ServiceAgentV1Impl.java:34)

**Comment by dbasch** [comment]
Hi Steve, are you using the main branch? The method addDocuments starts in
line 702 in the current version of the client.

Thanks,
Diego

**Comment by stevebuik** [comment]
Hi Diego,

we are using a slightly older version (not trunk) since we got a patch from
Adrian and are waiting for it to make it into trunk.

Regards, Steve Buikhuizen

Mob: +61 416426414

http://www.corporatecatapult.com

**Comment by dbasch** [comment]
What is the patch about? Without knowing what code you're running, I can't
really help you much :)

Diego

**Comment by stevebuik** [comment]
yeah sorry about the weak bug report. since we have a workaround it's not
urgent - but I thought it would be good for your team to be aware of.

The patch was a fix that allowed us to use Google Appengine url fetch to
call the indextank api. I don't know how it was recorded in github though.
If you discover that it is now in trunk then I can try upgrading sometime
soon.

Regards, Steve Buikhuizen

Mob: +61 416426414

http://www.corporatecatapult.com

**Comment by iladriano** [comment]
Hi Steve, dont worry about the bug report, it's been fixed on master.
Good catch BTW, thanks!
And IIRC (the original StackTrace confirms) you are using the current master (w/o the mentioned fix).
