### ISSUE TITLE
maven build

### ISSUE THREAD

**Issue by feniix** [flaptor/indextank-java#4]
Hi, I was bored and created a maven 2 build for the apiclient.

https://github.com/feniix/indextank-java/tree/mvn

Regards

**Comment by dbuthay** [comment]
Hi Feniix, 

we'll check it, and probably merge it next week. We'll keep you posted.

Thanks!

**Comment by loniszczuk** [comment]
Hi Feniix, thanks for your comments.

Your changes have been merged. Java client artifact info is
  <groupId>com.indextank</groupId>
  <artifactId>indextank-java</artifactId>
  <version>1.0.2</version>

We'll be updating the documentation soon.

Thanks!!
